
target:
	gcc -g -Wall -o es01 es01.c
	gcc -g -Wall -o es02 es02.c
	gcc -g -Wall -o es03 es03.c
	gcc -g -Wall -o es04 es04_threads.c -lrt
	gcc -g -Wall -o es05 es05.c -lpthread


clean:
	rm -rf es01 es02 es03 es04 es05

